---
- name: Deploy Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{DO_API_TOKEN}}"
    name: "{{inventory_hostname}}"
    size: s-1vcpu-512mb-10gb 
    region: fra1
    image: ubuntu-22-04-x64
    wait_timeout: 500
    ssh_keys: ['08:36:03:0a:a9:ed:35:8f:a5:78:53:8c:d0:c9:3c:d8']
  register: my_droplet

- name: Show Droplet info
  ansible.builtin.debug:
   msg: "{{ my_droplet.data.droplet.id }}"
   
- name: Update A record for www based on name/type/data
  community.digitalocean.digital_ocean_domain_record:
    state: present
    oauth_token: "{{DO_API_TOKEN}}"
    domain: fogcity.de
    ttl: 36
    type: A
    name: "{{inventory_hostname.split('.')[0] | lower }}"
    data: "{{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address | default('<none>', true) }}"
    force_update: yes